### ISSUE TITLE
Changing the background color..

### ISSUE THREAD

**Issue by jgknott** [arscan/encom-globe#10]
I've changed every css property I can.. I've also looked through most of the code, but I can't seem to find where to change the background color from black to white.  Any help would be greatly appreciated!

**Comment by arscan** [comment]
Happy to help, thanks for the interest in this project.

This is outside of the scope of what I thought people would want, so it does require changes to the source code and rebuilding using ```grunt build``` to make it work at this point.  A couple of things need to be changed, including:

* the default background, which is set in the threejs renderer
* the fog color for the globe and various items need to be changed to white (so they fade into the background);
* the text have a black stroke around the outside, which need to be removed/changed to white
* the satellites need to use colors that are visible against a white background

... and probably a few more things, depending on the look you are going for

I created a branch with the changes that could get you started.  See the [white-background branch](/arscan/encom-globe/tree/white-background).  The [diff for that branch](/arscan/encom-globe/compare/master...white-background) shows what I changed.

This is what those changes look like:

![screen shot 2016-01-25 at 10 20 46 pm](https://cloud.githubusercontent.com/assets/412901/12571823/12ec4d78-c3b3-11e5-8a3e-41eb2c6c1e59.png)

It probably could look better than this -- I feel like the right color palette needs to be used on the hex tiles.  And I think that hex tile color randomizer darkens them by default, which might be a bad choice with the white background.  Definitely worth some experimentation.

Hopefully this is helpful. Let me know if there are other parts you'd like to change that you are having trouble locating.  If you come up with something that looks good I can probably roll these changes back into master as configurable options.

**Comment by jgknott** [comment]
This is great! Thanks for the quick and thorough response. I'll play around with it and see what I can come up with :)

**Comment by arscan** [comment]
Glad to help, good luck! :four_leaf_clover:

**Comment by arscan** [comment]
Cleaning up issues -- closing this one.  I'll leave the branch for people to see in the future... or at least until I do the next refactor that makes this obsolete.

**Comment by beags121** [comment]
Hi @arscan  - I've downloaded https://github.com/arscan/encom-globe/tree/white-background but it still seems to be running with the same black background despite the changes. Please can you revisit and advise?

Many thanks.
