### ISSUE TITLE
Very bad performance on mobile

### ISSUE THREAD

**Issue by jjant** [arscan/encom-globe#14]
I'm trying to figure out with this works really badly on mobile, frames drop to like 3fps. Any ideas on how to fix this?

**Comment by arscan** [comment]
Not sure, works fine on my samsung galaxy s6, and i haven't seen it run particularly slow on any 'modern' (<3 years old) "flagship" smartphone.  What are you running it on?

**Comment by jjant** [comment]
@arscan An iPhone7 :( I've tried both Safari and Chrome. Pretty strange.

**Comment by arscan** [comment]
That is strange.  I'll see if I can grab one of my friends' iPhones to see what it looks like.  Is this just on the demo page, or something you are working on?

**Comment by jjant** [comment]
Both: I've tried https://www.robscanlon.com/encom-globe/ and also a modified version I'm working on. I've also tried using `experimental-webgl` to see if that changed anything, but no luck.

**Comment by geekkid1** [comment]
I’m getting the same problem on my iPhone 6S+

**Comment by dejvid** [comment]
Any progress on this? HAs anyone solved this? There seems to be a problem with the WebGL driver of iPhone... because it happens only after few seconds, before that it loads perfectly smooth. Haven't found the code in the project that causes this.
