### ISSUE TITLE
Add image as texture?

### ISSUE THREAD

**Issue by jjant** [arscan/encom-globe#15]
I would like to use an image as texture (as webGL Globe uses) for the globe (in addition to the hex grid).

Is this possible? I couldn't find a way to do it from the code.

Also, how could one generate a different hex grid (`data.js` file)?

**Comment by arscan** [comment]
I would just create a THREE.Sphere the same size as the globe, add a texture, and add it to the scene. There should be plenty of examples of doing that in three.js.

The data.js file is generated from https://github.com/arscan/hexasphere.js.
