### ISSUE TITLE
Font preference not honoured

### ISSUE THREAD

**Issue by netsgnut** [arscan/encom-globe#4]
It seems that specifying the `font` won't change how the pin/marker labels are rendered. The reason is that the option is not passed to `Pin` and `Marker` at all.

Would you like a PR that fixes that? Thanks.

**Comment by arscan** [comment]
Hey @netsgnut, sure, I'd gladly except any PRs.  I'll be disconnected for a week on vacation, so it may take me a little bit to merge it in though.  Thanks for your help!

**Comment by netsgnut** [comment]
Thanks @arscan! Will try to get it in by tonight. Probably with a separate one that deals with #5 too, but I guess that one needs some more discussions.
