### ISSUE TITLE
Bower installation failed

### ISSUE THREAD

**Issue by netsgnut** [arscan/encom-globe#5]
The installation log would look something like this now:

```bash
bower encom-globe#v0.6.2        cached git://github.com/arscan/encom-globe.git#0.6.2
bower encom-globe#v0.6.2      validate 0.6.2 against git://github.com/arscan/encom-globe.git#v0.6.2
bower threejs#r66           not-cached git://github.com/mrdoob/three.js.git#r66
bower threejs#r66              resolve git://github.com/mrdoob/three.js.git#r66
bower TweenJS#release_v0.5.1       not-cached git://github.com/CreateJS/TweenJS.git#release_v0.5.1
bower TweenJS#release_v0.5.1          resolve git://github.com/CreateJS/TweenJS.git#release_v0.5.1
bower quadtree2#*                      cached git://github.com/burninggramma/quadtree2.js.git#0.5.5
bower quadtree2#*                    validate 0.5.5 against git://github.com/burninggramma/quadtree2.js.git#*
bower vec2#*                           cached git://github.com/tmpvar/vec2.js.git#1.6.0
bower vec2#*                         validate 1.6.0 against git://github.com/tmpvar/vec2.js.git#*
bower threejs#r66                    download https://github.com/mrdoob/three.js/archive/r66.tar.gz
bower threejs#r66                    progress received 9.1MB of 83.6MB downloaded, 11%
bower threejs#r66                    progress received 11.3MB of 83.6MB downloaded, 14%
bower threejs#r66                    progress received 13.3MB of 83.6MB downloaded, 16%
bower threejs#r66                    progress received 15.6MB of 83.6MB downloaded, 19%
bower threejs#r66                    progress received 17.6MB of 83.6MB downloaded, 21%
bower threejs#r66                    progress received 19.8MB of 83.6MB downloaded, 24%
bower threejs#r66                    progress received 21.9MB of 83.6MB downloaded, 26%
bower threejs#r66                    progress received 24.3MB of 83.6MB downloaded, 29%
bower threejs#r66                    progress received 26.6MB of 83.6MB downloaded, 32%
bower TweenJS#release_v0.5.1     ENORESTARGET Tag/branch release_v0.5.1 does not exist
```

In our case, it is probably a good idea to leave the dependencies blank at the `bower.json` as it is not needed - a typical library user would use the compiled sources with dependencies included, and we can keep the `package.json` for all those development purposes.

**Comment by arscan** [comment]
I'm interested in any recommendations you have.  I haven't really used bower in practice, so I wouldn't be surprised if I did this wrong.  Any documentation / reference (to a major js library) would be helpful for anything you recommend though.

**Comment by netsgnut** [comment]
Sure. In the environment that I am using here (particularly in one of the more shinier example that I get involved into recently), we use NPM for the server-side packages and allow Bower to manage our client libraries. I guess it is (still) quite a common practice.

In our case here, the repository contains the compiled sources, which I would argue that is what one would usually use if they include your library through Bower. That seems conveniently enough as a drop-in solution.

Judging from the commits, I think currently NPM is used for most of the development purposes, as the Bower, despite the higher version number, has some number of outdated dependencies. In that case, I would suggest the following, preferably from the next version:

1. For each development cycle use npm/package.json to manage the dependencies. Start with a clean bower.json dependencies.
2. Whenever a new version gets released, bump both the version number as specified by `package.json` and `bower.json`[1], at the same time re-build `encom-globe(.min).js` (and probably `data.js` and `grid.js`). Tag the release commit and push the tag as well (just like before). That way you can synchronize the versions between NPM/Bower, without letting each of them getting into each other's way.

So at the end, a bower release probably would just contain `encom-globe.js`, `encom-globe.min.js`, `data.js` and `grid.js` (`LICENSE` and `README.md` as well maybe), all generated whenever a new version gets released.

One of the examples of a big-name libraries that I have in mind right now with this sort of workflow is React. The main repository lives at https://github.com/facebook/react but the bower-ized package lives at https://github.com/reactjs/react-bower, auto-generated and pushed by one of the devs whenever a version gets bumped. You can note their [bower.json at reactjs/react-bower](https://github.com/reactjs/react-bower/blob/master/bower.json) and [package.json at facebook/react](https://github.com/facebook/react/blob/master/package.json) for comparison.

[1] Optionally, the version number at `bower.json` needs not be specified. The process is kind of automatic as long as the tags are pushed appropriately. See react example.

**Comment by netsgnut** [comment]
For the records you may want to have a look at the [bower.json on my testing branch](https://github.com/netsgnut/encom-globe/blob/issue-5/bower.json). If you like you can as well test my branch with a bower.json of version specification "netsgnut/issue-5". Be noted that in that test commit I haven't really compiled the sources, though.

**Comment by arscan** [comment]
Weird, I'm not sure why I chose to include those dependencies, as it seems pretty obvious to me now that they are baked into the built sources.  Thanks for explaining that to me.

I like how react puts the bower-friendly version into a separate repo.  I recall being really annoyed trying to use three.js in bower last year, since it would download the entire (large) git repo, 99% of which is examples and old commits.  By splitting it into its own repo it avoids downloading all that unnecessary stuff.

You meant put in the version specification of "netsgnut/encom-globe#issue-5" right?  That looks good to me; if you want to open a pull request I'll bring that in.  Will I need to update the bower version of the package?

Thanks for your help!

**Comment by netsgnut** [comment]
Oh I should have worded better: for now you may test my branch with a `bower.json` like this:
```json
{
  "name": "test",
  "dependencies": {
    "encom-globe": "netsgnut/issue-5"
  }
}
```
Upon `bower install`, `bower_components/encom-globe` should contain our testing package then.

---

I will open a pull request with only the bower.json to keep things clean. Once in you may want to recompile the sources, add the compiled files, update `package.json` version (probably bumping a minor?), commit and tag version.

And no, just update the `package.json` version is enough, as [bower uses git tags for versioning, which means for now `version` is ignored](https://github.com/bower/bower.json-spec#version). That way both npm (for development) and bower (for deployment) will be happy ;)

Oh yes, thanks for the awesome library :)

**Comment by arscan** [comment]
Glad you like it.  Thanks again!

**Comment by netsgnut** [comment]
Awesome! Thanks!
(P.S. I think we will have to git tag it and recompile it too :+1: )
